---
title: "kmeans & EM"
author: "Kehinde Fagbamigbe"
date: "2023-01-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
old_clusters <- rep(NA,4)
old_clusters
```

```{r}
class(old_clusters)
```

```{r}
class(NA)
```


```{r}


#function to calculate euclidean distance
euclidean_distance <- function(X, Y){
  dist <- sqrt(sum((X - Y) ^ 2))
  return(dist) #returns euclidean distance between two points or two vectors
}


# Function to perform k-means clustering
kmeans <- function(x, k) {
  
  # Select k random observations as initial centroids
  centroids <- x[sample(1:nrow(x), size = k, replace = TRUE), ]
  
  # creating dummy clusters
  clusters <- rep(list(data.frame(matrix(ncol = ncol(x), nrow = 0))), k)


  # Initialize empty clusters and old centroids
  old_clusters <- rep(NA, nrow(x))
  old_centroids <- matrix(NA, nrow = k, ncol = ncol(x))

  # Repeat the following steps until convergence
  while (TRUE) {
    # Assign each observation to the cluster with the nearest centroid
    for (j in 1:nrow(x)) {
      
      # Calculate the distance between the observation and each centroid
      distances <- sapply(1:k, function(i) euclidean_distance(x[j,], centroids[i,]))
      
      # Find the index of the nearest centroid
      cluster <- which.min(distances)
      
      # Add the observation to the corresponding cluster
      clusters[[cluster]] <- rbind(clusters[[cluster]], x[j,])
    }

    # Check if the clusters have changed
    if (identical(old_clusters, clusters)) { 
      break # Exit the loop if the clusters have not changed
    }

    # Check for empty clusters
    empty_clusters <- which(sapply(clusters, nrow) == 0)

    if (length(empty_clusters) > 0) {
      # Select new random centroid for empty cluster
      random_center_index <- sample(1:nrow(x), size = length(empty_clusters), replace = TRUE)
      centroids[empty_clusters, ] <- x[random_center_index, ]
    }

    # Check for infinite loop
    if (identical(old_centroids, centroids)) {
      break # Exit the loop if the centroids have not changed
    }
    old_centroids <- centroids

    # Update the centroids
    for (i in 1:k) {
      centroids[i, ] <- colMeans(clusters[[i]])
    }

    old_clusters <- clusters
  }

  return(list(clusters = clusters, centroids = centroids))
}

```


```{r}
source("/Users/alhajidot/Documents/BGSU/Project/EMScript.R")
```


```{r}
x <- read.table("/Users/alhajidot/Documents/BGSU/Project/gaussian.txt", quote="\"", comment.char="")
head(x)
```


```{r}
trial = kmeans(x, 2)
trial
```



